### ISSUE TITLE
[solr] extraEnvVars results in invalid yaml

### ISSUE THREAD

**Issue by codablock** [PreferredAI/helm-charts#15]
**Affected chart**: 
solr 2.3.2

**Describe the bug**
When using `extraEnvVars`, the statefulset becomes invalid due to new-line issues. Example invalid yaml:
```
...
         env:
            - name: "SOLR_JAVA_MEM"
              value: "-Xms2g -Xmx3g"
            - name: "SOLR_HOME"
              value: "/opt/solr/server/home"
            - name: "SOLR_PORT"
              value: "8983"
            - name: "POD_HOSTNAME"
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: "SOLR_HOST"
              value: "$(POD_HOSTNAME).solr-dataservice-headless.test-blue-base-persistency"
            - name: "ZK_HOST"
              value: "solr-dataservice-zookeeper-headless:2181"
            - name: "SOLR_LOG_LEVEL"
              value: "INFO"            - name: SOLR_OPTS
              value: -Dsolr.autoSoftCommit.maxTime=60000 -Dsolr.autoCommit.maxTime=30000 -Dupdate.autoCreateFields=false
...
```
**To Reproduce**
Add `extraEnvVars` to your values.

**Expected behavior**
Results in a valid statefulset being deployed.
