### ISSUE TITLE
[solr] wrong affinity yaml indentation

### ISSUE THREAD

**Issue by tom-schoener** [PreferredAI/helm-charts#22]
**Affected chart**
solr

**Describe the bug**
It's not possible to set the affinity config for the solr statefulset. The rendered template looks like this and is invalid:

``` yaml
...
      spec:
        affinity:        podAntiAffinity:
            preferredDuringSchedulingIgnoredDuringExecution:
            - podAffinityTerm:
                labelSelector:
                  matchExpressions:
                  - key: app.kubernetes.io/name
                    operator: In
                    values:
                    - solr
                topologyKey: kubernetes.io/hostname
              weight: 100
...
```

The `indent` function should actually be: `nindent`. This might affect other configs, too.

**To Reproduce**
Add this to your `values.yaml` file and render the template:

```yaml
affinity:
  podAntiAffinity:
    preferredDuringSchedulingIgnoredDuringExecution:
      - weight: 100
        podAffinityTerm:
          labelSelector:
            matchExpressions:
              - key: app.kubernetes.io/name
                operator: In
                values:
                  - solr
          topologyKey: "kubernetes.io/hostname"
```

**Expected behavior**
Should have correct indentation. 

**Screenshots**

**Helm and Kubernetes**:
- Output of `helm version`:
```
version.BuildInfo{Version:"v3.5.2", GitCommit:"167aac70832d3a384f65f9745335e9fb40169dc2", GitTreeState:"dirty", GoVersion:"go1.15.7"}
```
- Output of `kubectl version`:
```
Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.3", GitCommit:"1e11e4a2108024935ecfcb2912226cedeafd99df", GitTreeState:"clean", BuildDate:"2020-10-14T12:50:19Z", GoVersion:"go1.15.2", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"17+", GitVersion:"v1.17.14-gke.1600", GitCommit:"7c407f5cc8632f9af5a2657f220963aa7f1c46e7", GitTreeState:"clean", BuildDate:"2020-12-07T09:22:27Z", GoVersion:"go1.13.15b4", Compiler:"gc", Platform:"linux/amd64"}
```
